/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StatusSlugRouteImport } from './routes/status/$slug'
import { Route as InvitesTokenRouteImport } from './routes/invites/$token'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedStatusPagesRouteImport } from './routes/_authenticated/status-pages'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedIncidentsRouteImport } from './routes/_authenticated/incidents'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChannelsRouteImport } from './routes/_authenticated/channels'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as StatusUnsubscribeTokenRouteImport } from './routes/status/unsubscribe/$token'
import { Route as StatusConfirmTokenRouteImport } from './routes/status/confirm/$token'
import { Route as AuthenticatedStatusPagePageIdRouteImport } from './routes/_authenticated/status-page/$pageId'
import { Route as AuthenticatedMonitorMonitorIdRouteImport } from './routes/_authenticated/monitor/$monitorId'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusSlugRoute = StatusSlugRouteImport.update({
  id: '/status/$slug',
  path: '/status/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitesTokenRoute = InvitesTokenRouteImport.update({
  id: '/invites/$token',
  path: '/invites/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStatusPagesRoute =
  AuthenticatedStatusPagesRouteImport.update({
    id: '/status-pages',
    path: '/status-pages',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIncidentsRoute = AuthenticatedIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChannelsRoute = AuthenticatedChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const StatusUnsubscribeTokenRoute = StatusUnsubscribeTokenRouteImport.update({
  id: '/status/unsubscribe/$token',
  path: '/status/unsubscribe/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusConfirmTokenRoute = StatusConfirmTokenRouteImport.update({
  id: '/status/confirm/$token',
  path: '/status/confirm/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStatusPagePageIdRoute =
  AuthenticatedStatusPagePageIdRouteImport.update({
    id: '/status-page/$pageId',
    path: '/status-page/$pageId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMonitorMonitorIdRoute =
  AuthenticatedMonitorMonitorIdRouteImport.update({
    id: '/monitor/$monitorId',
    path: '/monitor/$monitorId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/channels': typeof AuthenticatedChannelsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/incidents': typeof AuthenticatedIncidentsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/status-pages': typeof AuthenticatedStatusPagesRoute
  '/team': typeof AuthenticatedTeamRoute
  '/auth/login': typeof AuthLoginRoute
  '/invites/$token': typeof InvitesTokenRoute
  '/status/$slug': typeof StatusSlugRoute
  '/monitor/$monitorId': typeof AuthenticatedMonitorMonitorIdRoute
  '/status-page/$pageId': typeof AuthenticatedStatusPagePageIdRoute
  '/status/confirm/$token': typeof StatusConfirmTokenRoute
  '/status/unsubscribe/$token': typeof StatusUnsubscribeTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/channels': typeof AuthenticatedChannelsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/incidents': typeof AuthenticatedIncidentsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/status-pages': typeof AuthenticatedStatusPagesRoute
  '/team': typeof AuthenticatedTeamRoute
  '/auth/login': typeof AuthLoginRoute
  '/invites/$token': typeof InvitesTokenRoute
  '/status/$slug': typeof StatusSlugRoute
  '/monitor/$monitorId': typeof AuthenticatedMonitorMonitorIdRoute
  '/status-page/$pageId': typeof AuthenticatedStatusPagePageIdRoute
  '/status/confirm/$token': typeof StatusConfirmTokenRoute
  '/status/unsubscribe/$token': typeof StatusUnsubscribeTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/channels': typeof AuthenticatedChannelsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/incidents': typeof AuthenticatedIncidentsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/status-pages': typeof AuthenticatedStatusPagesRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/auth/login': typeof AuthLoginRoute
  '/invites/$token': typeof InvitesTokenRoute
  '/status/$slug': typeof StatusSlugRoute
  '/_authenticated/monitor/$monitorId': typeof AuthenticatedMonitorMonitorIdRoute
  '/_authenticated/status-page/$pageId': typeof AuthenticatedStatusPagePageIdRoute
  '/status/confirm/$token': typeof StatusConfirmTokenRoute
  '/status/unsubscribe/$token': typeof StatusUnsubscribeTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/billing'
    | '/channels'
    | '/dashboard'
    | '/incidents'
    | '/settings'
    | '/status-pages'
    | '/team'
    | '/auth/login'
    | '/invites/$token'
    | '/status/$slug'
    | '/monitor/$monitorId'
    | '/status-page/$pageId'
    | '/status/confirm/$token'
    | '/status/unsubscribe/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/billing'
    | '/channels'
    | '/dashboard'
    | '/incidents'
    | '/settings'
    | '/status-pages'
    | '/team'
    | '/auth/login'
    | '/invites/$token'
    | '/status/$slug'
    | '/monitor/$monitorId'
    | '/status-page/$pageId'
    | '/status/confirm/$token'
    | '/status/unsubscribe/$token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/billing'
    | '/_authenticated/channels'
    | '/_authenticated/dashboard'
    | '/_authenticated/incidents'
    | '/_authenticated/settings'
    | '/_authenticated/status-pages'
    | '/_authenticated/team'
    | '/auth/login'
    | '/invites/$token'
    | '/status/$slug'
    | '/_authenticated/monitor/$monitorId'
    | '/_authenticated/status-page/$pageId'
    | '/status/confirm/$token'
    | '/status/unsubscribe/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  InvitesTokenRoute: typeof InvitesTokenRoute
  StatusSlugRoute: typeof StatusSlugRoute
  StatusConfirmTokenRoute: typeof StatusConfirmTokenRoute
  StatusUnsubscribeTokenRoute: typeof StatusUnsubscribeTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status/$slug': {
      id: '/status/$slug'
      path: '/status/$slug'
      fullPath: '/status/$slug'
      preLoaderRoute: typeof StatusSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invites/$token': {
      id: '/invites/$token'
      path: '/invites/$token'
      fullPath: '/invites/$token'
      preLoaderRoute: typeof InvitesTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/status-pages': {
      id: '/_authenticated/status-pages'
      path: '/status-pages'
      fullPath: '/status-pages'
      preLoaderRoute: typeof AuthenticatedStatusPagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/incidents': {
      id: '/_authenticated/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof AuthenticatedIncidentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/channels': {
      id: '/_authenticated/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof AuthenticatedChannelsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/status/unsubscribe/$token': {
      id: '/status/unsubscribe/$token'
      path: '/status/unsubscribe/$token'
      fullPath: '/status/unsubscribe/$token'
      preLoaderRoute: typeof StatusUnsubscribeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status/confirm/$token': {
      id: '/status/confirm/$token'
      path: '/status/confirm/$token'
      fullPath: '/status/confirm/$token'
      preLoaderRoute: typeof StatusConfirmTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/status-page/$pageId': {
      id: '/_authenticated/status-page/$pageId'
      path: '/status-page/$pageId'
      fullPath: '/status-page/$pageId'
      preLoaderRoute: typeof AuthenticatedStatusPagePageIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/monitor/$monitorId': {
      id: '/_authenticated/monitor/$monitorId'
      path: '/monitor/$monitorId'
      fullPath: '/monitor/$monitorId'
      preLoaderRoute: typeof AuthenticatedMonitorMonitorIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedChannelsRoute: typeof AuthenticatedChannelsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedIncidentsRoute: typeof AuthenticatedIncidentsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStatusPagesRoute: typeof AuthenticatedStatusPagesRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedMonitorMonitorIdRoute: typeof AuthenticatedMonitorMonitorIdRoute
  AuthenticatedStatusPagePageIdRoute: typeof AuthenticatedStatusPagePageIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedChannelsRoute: AuthenticatedChannelsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedIncidentsRoute: AuthenticatedIncidentsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStatusPagesRoute: AuthenticatedStatusPagesRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedMonitorMonitorIdRoute: AuthenticatedMonitorMonitorIdRoute,
  AuthenticatedStatusPagePageIdRoute: AuthenticatedStatusPagePageIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  InvitesTokenRoute: InvitesTokenRoute,
  StatusSlugRoute: StatusSlugRoute,
  StatusConfirmTokenRoute: StatusConfirmTokenRoute,
  StatusUnsubscribeTokenRoute: StatusUnsubscribeTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
